package interfacesGraficas;

import clases.Producto;
import imagenes.PosicionImagenes;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cesar
 */
public class ProductosFrom extends javax.swing.JFrame {
    PosicionImagenes imagenes = new PosicionImagenes();
    
    //Productos
    
    // Array de nombres de productos
        String Productos [] = {"Leche", "Huevos", "Pan", "Arroz", "Pasta", "Aceite de oliva", "Tomates enlatados", "Atún en lata",
                "Cereal", "Yogur", "Queso", "Pollo", "Carne de res", "Pescado", "Manzana", "Plátano", "Naranjas", "Zanahorias",
                "Cebollas", "Papas", "Espinacas", "Brócoli", "Lechuga", "Zumo de naranja", "Galletas", "Café", "Té",
                "Azúcar", "Sal", "Sopa enlatada", "Papel higiénico", "Detergente", "Jabón de manos", "Cepillo de dientes",
                "Pasta de dientes", "Shampoo", "Acondicionador", "Toallas de papel"};

        // Array de precios correspondientes (precios generados aleatoriamente para este ejemplo)
        double precios [] = {2.50, 1.75, 2.00, 3.50, 1.20, 4.50, 1.80, 2.25, 4.00, 2.75, 5.50, 8.00, 10.50, 7.80, 1.25,
                0.75, 1.50, 0.90, 1.20, 1.00, 1.50, 2.00, 2.50, 1.80, 3.00, 2.80, 6.00, 4.20, 2.30, 1.50, 1.00, 1.75,
                2.50, 3.00, 1.25, 1.50, 4.00, 3.50, 2.25, 2.50};
        
        ArrayList<Producto> listaVentas = new ArrayList<Producto>();
        
        double PRECIO =0;
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        int cantidads;
    /**
     * Creates new form ProductosFrom
     */
    public ProductosFrom() {
        initComponents();
        imagenes.escaralarLabel(logo, "/imagenes/logome.png");
        imagenes.escaralarLabel(labelRegresar, "/imagenes/regresar.png");
        //imagenes.escaralarLabel(agregar, "/imagenes/agregar.jpg");
        DefaultComboBoxModel comboMode = new DefaultComboBoxModel(Productos);
        opcionesProducto.setModel(comboMode);
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO U.");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("IMPORTE");
        setLocationRelativeTo(null);
        ActualizarRegistros();
        CalcularPrecios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelTitutlo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        labelImporte = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelProducto = new javax.swing.JLabel();
        labelRIVA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        opcionesProducto = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JSpinner();
        labelPrecio = new javax.swing.JLabel();
        labelIva = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        labelRtotal = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        labelRSubTotal1 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        labelRegresar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitutlo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitutlo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitutlo.setText("    Catalogo de Productos");
        panelPrincipal.add(labelTitutlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 300, 70));
        panelPrincipal.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 320, 20));

        labelImporte.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelImporte.setForeground(new java.awt.Color(0, 0, 0));
        labelImporte.setText("Importe");
        panelPrincipal.add(labelImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 80, 40));

        labelCantidad.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        labelCantidad.setText("Cantidad");
        panelPrincipal.add(labelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, 40));

        labelProducto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelProducto.setForeground(new java.awt.Color(0, 0, 0));
        labelProducto.setText("Producto");
        panelPrincipal.add(labelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 80, 40));

        labelRIVA.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelRIVA.setForeground(new java.awt.Color(0, 0, 0));
        labelRIVA.setText("$0.00 PE");
        panelPrincipal.add(labelRIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, 120, 40));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 720, 300));

        opcionesProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opcionesProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesProductoActionPerformed(evt);
            }
        });
        panelPrincipal.add(opcionesProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, 30));

        cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadStateChanged(evt);
            }
        });
        panelPrincipal.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, -1));

        labelPrecio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelPrecio.setForeground(new java.awt.Color(0, 0, 0));
        labelPrecio.setText("Precio");
        panelPrincipal.add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 60, 40));

        labelIva.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelIva.setForeground(new java.awt.Color(0, 0, 0));
        labelIva.setText("IVA");
        panelPrincipal.add(labelIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 80, 40));

        labelTotal.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelTotal.setText("Total");
        panelPrincipal.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 740, 80, 40));

        labelSubtotal.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        labelSubtotal.setText("Sub total");
        panelPrincipal.add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 80, 40));

        labelRtotal.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelRtotal.setForeground(new java.awt.Color(0, 0, 0));
        labelRtotal.setText("$0.00 PE");
        panelPrincipal.add(labelRtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 740, 120, 40));

        precio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setText("$0.00 PE");
        panelPrincipal.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 140, 40));

        labelRSubTotal1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelRSubTotal1.setForeground(new java.awt.Color(0, 0, 0));
        labelRSubTotal1.setText("$0.00 PE");
        panelPrincipal.add(labelRSubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 120, 40));

        precio1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        precio1.setForeground(new java.awt.Color(0, 0, 0));
        precio1.setText("$0.00 PE");
        panelPrincipal.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 140, 40));

        agregar.setForeground(new java.awt.Color(0, 0, 0));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        panelPrincipal.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 110, 90));

        logo.setText("logo");
        panelPrincipal.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 170, 110));

        labelRegresar.setForeground(new java.awt.Color(0, 0, 0));
        labelRegresar.setText("jLabel1");
        labelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegresarMouseClicked(evt);
            }
        });
        panelPrincipal.add(labelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 70));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html>Procesar Compra <html>");
        panelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, 150, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegresarMouseClicked
        // TODO add your handling code here:
        Cuenta_cliente_form llamadaCliente = new Cuenta_cliente_form();
        llamadaCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelRegresarMouseClicked

    private void opcionesProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesProductoActionPerformed
        // TODO add your handling code here:
        CalcularPrecios();
        
        
    }//GEN-LAST:event_opcionesProductoActionPerformed

    private void cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadStateChanged
        CalcularPrecios();

        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadStateChanged

    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        Producto productos = new Producto();
        
        productos.setId(opcionesProducto.getSelectedIndex());
        productos.setDescripcion(opcionesProducto.getSelectedItem().toString());
        productos.setPrecio(PRECIO);
        productos.setCantidad(cantidads);
        productos.setImporte(PRECIO*cantidads);
        if(!BuscarVenta(productos)){
            listaVentas.add(productos);
        }
        
        ActualizarRegistros();
        borrarVenta();
        
    }//GEN-LAST:event_agregarActionPerformed

    public boolean BuscarVenta (Producto nueva){
        
        for(Producto p : listaVentas){
            
            if(p.getId()==nueva.getId()){
                
                int nuevaCantidad = p.getCantidad()+nueva.getCantidad();
                p.setCantidad(nuevaCantidad);
                p.setImporte(p.getPrecio()*nuevaCantidad);
                return true;
            
            }
        
        }
        return false;
        
    }
    
    public void borrarVenta (){
        
        PRECIO=0;
        cantidads=1;
        precio1.setText(monedas(0));
        precio.setText(monedas(0));
        opcionesProducto.setSelectedIndex(0);
        cantidad.setValue(1);
        CalcularPrecios();

    
    }
    public void CalcularPrecios(){
        
        PRECIO = precios[opcionesProducto.getSelectedIndex()];
        cantidads = Integer.parseInt(cantidad.getValue().toString());
        precio1.setText(monedas(PRECIO));
        precio.setText(monedas(PRECIO*cantidads));
    }
    
    public String monedas(double PRECIO){
        
        return "$ "+Math.round(PRECIO*100.0)/100.0+" PE";
    
    }
    
    public void ActualizarRegistros(){
        while(modelo.getRowCount()>0){
            
            modelo.removeRow(0);
        }
        double subTotal =0;
        for (Producto p : listaVentas){
            
            Object x [] = new Object[4];
            x[0] =p.getDescripcion();
            x[1] =monedas(p.getPrecio());
            x[2] =p.getCantidad();
            x[3] =monedas(p.getImporte());
            subTotal+=p.getImporte();
            modelo.addRow(x);
            
        }
        
        double iva =subTotal*0.16;
        double total = subTotal+iva;
        labelRSubTotal1.setText(monedas(subTotal));
        labelRIVA.setText(monedas(iva));
        labelRtotal.setText(monedas(total));
        
    
        tblProductos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelImporte;
    private javax.swing.JLabel labelIva;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelRIVA;
    private javax.swing.JLabel labelRSubTotal1;
    private javax.swing.JLabel labelRegresar;
    private javax.swing.JLabel labelRtotal;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTitutlo;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> opcionesProducto;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precio1;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
