package interfacesGraficas;

import BaseDatos.frmRegistrase;
import BaseDatos.hash;
import BaseDatos.sqlUsuarios;
import BaseDatos.usuarios;
import imagenes.PosicionImagenes;
import java.awt.Color;
import java.beans.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cesar
 */
public class Prototipo extends javax.swing.JFrame {
    
    PosicionImagenes imagen = new PosicionImagenes();

    /**
     * Creates new form Prototipo
     */
    public Prototipo() {
        initComponents();
        //imagen.escaralarLabel(labelLogo, "logo.png");
        imagen.escaralarLabel(labelNosotros, "Sobre Nosotros.png");
        imagen.escaralarLabel(labelDecoracion, "decoracion1.jpg");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelPasword = new javax.swing.JLabel();
        separaupassword = new javax.swing.JSeparator();
        separadorusuario = new javax.swing.JSeparator();
        txtusuario = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        labelNosotros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUusario3 = new javax.swing.JLabel();
        panelInciarSesion = new javax.swing.JPanel();
        labelentrar = new javax.swing.JLabel();
        panelRegistrarse = new javax.swing.JPanel();
        labelRegistrarse = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        labelDecoracion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSlir = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("MegaMarket");
        panelPrincipal.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 300, 80));

        labelPasword.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelPasword.setForeground(new java.awt.Color(0, 0, 0));
        labelPasword.setText("Contraseña");
        labelPasword.setToolTipText("Usuario");
        panelPrincipal.add(labelPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, -1));
        panelPrincipal.add(separaupassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 260, 20));
        panelPrincipal.add(separadorusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, 20));

        txtusuario.setBackground(new java.awt.Color(0, 0, 0));
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 340, 40));

        txtpassword.setBackground(new java.awt.Color(0, 0, 0));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 340, 40));
        panelPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        labelNosotros.setText("jLabel4");
        labelNosotros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNosotros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNosotrosMouseClicked(evt);
            }
        });
        panelPrincipal.add(labelNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 360, 290));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Presionar la imagen, para mas informacion ");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 360, -1));

        labelUusario3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelUusario3.setForeground(new java.awt.Color(0, 0, 0));
        labelUusario3.setText("Usuario");
        labelUusario3.setToolTipText("Usuario");
        panelPrincipal.add(labelUusario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, -1));

        panelInciarSesion.setBackground(new java.awt.Color(255, 255, 255));

        labelentrar.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelentrar.setForeground(new java.awt.Color(0, 0, 0));
        labelentrar.setText("     Inicar Sesion");
        labelentrar.setToolTipText("Usuario");
        labelentrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelentrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelentrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelentrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelentrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelInciarSesionLayout = new javax.swing.GroupLayout(panelInciarSesion);
        panelInciarSesion.setLayout(panelInciarSesionLayout);
        panelInciarSesionLayout.setHorizontalGroup(
            panelInciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInciarSesionLayout.createSequentialGroup()
                .addComponent(labelentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelInciarSesionLayout.setVerticalGroup(
            panelInciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelentrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelInciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 270, 60));

        panelRegistrarse.setBackground(new java.awt.Color(0, 0, 0));

        labelRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        labelRegistrarse.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrarse.setText("                              Registrarse");
        labelRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarseLayout = new javax.swing.GroupLayout(panelRegistrarse);
        panelRegistrarse.setLayout(panelRegistrarseLayout);
        panelRegistrarseLayout.setHorizontalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegistrarseLayout.setVerticalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPrincipal.add(panelRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 40));
        panelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 320, 30));

        labelDecoracion.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDecoracion, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDecoracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 410, 300));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        labelSlir.setBackground(new java.awt.Color(0, 0, 0));
        labelSlir.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelSlir.setForeground(new java.awt.Color(255, 255, 255));
        labelSlir.setText("    X");
        labelSlir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSlir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSlirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelSlir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelSlir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 865, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelentrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelentrarMouseClicked
        // TODO add your handling code here:
        
        sqlUsuarios modSql = new sqlUsuarios();
        usuarios mod = new usuarios();
        
        String pass = new String(txtpassword.getPassword());
        
        if(!txtusuario.getText().equals("") && !pass.equals("")){
            
            String nuevoPass = hash.sha1(pass);
            
            mod.setUsuario(txtusuario.getText());
            mod.setPassword(nuevoPass);
            
            if (modSql.Login(mod)){
                
                Cuenta_cliente_form llamadaProductos = new  Cuenta_cliente_form();
                llamadaProductos.setVisible(true);
                this.setVisible(false);
                
            }else{
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");

        }
        
        
        
        
        //String usuario =txtusuario.getText();
        //String password = txtpassword.getText();
        
        
        panelInciarSesion.setBackground(Color.BLACK);
        labelentrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelentrarMouseClicked

    private void labelentrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelentrarMouseExited
        // TODO add your handling code here:
        panelInciarSesion.setBackground(Color.WHITE);
        labelentrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_labelentrarMouseExited

    private void labelentrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelentrarMousePressed
        // TODO add your handling code here:
               // panelInciarSesion.setBackground(Color.BLUE);

    }//GEN-LAST:event_labelentrarMousePressed

    private void labelNosotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNosotrosMouseClicked
        // TODO add your handling code here:
        Informacion_empresaForm llamada = new Informacion_empresaForm();
        llamada.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_labelNosotrosMouseClicked

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void labelRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarseMouseClicked
        // TODO add your handling code here:
        frmRegistrase registrarse = new frmRegistrase();
        registrarse.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_labelRegistrarseMouseClicked

    private void labelSlirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSlirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labelSlirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prototipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelDecoracion;
    private javax.swing.JLabel labelNosotros;
    private javax.swing.JLabel labelPasword;
    private javax.swing.JLabel labelRegistrarse;
    private javax.swing.JLabel labelSlir;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUusario3;
    private javax.swing.JLabel labelentrar;
    private javax.swing.JPanel panelInciarSesion;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRegistrarse;
    private javax.swing.JSeparator separadorusuario;
    private javax.swing.JSeparator separaupassword;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
