/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaseDatos;

import imagenes.PosicionImagenes;
import interfacesGraficas.Prototipo;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class frmRegistrase extends javax.swing.JFrame {

    PosicionImagenes imagenes = new PosicionImagenes();

    /**
     * Creates new form frmRegistrase
     */
    public frmRegistrase() {
        initComponents();
        imagenes.escaralarLabel(labelImagen, "/imagenes/registrarse.jpg");
        imagenes.escaralarLabel(labelRegresar, "/imagenes/regresarMorado.png");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        panelFondoIma = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelConfirPass = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtConfirmarPass = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        LabelRegisclick = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelRegresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 51, 255));
        LabelUsuario.setText("Usuario");
        panelPrincipal.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 50));

        labelImagen.setText("jLabel2");

        javax.swing.GroupLayout panelFondoImaLayout = new javax.swing.GroupLayout(panelFondoIma);
        panelFondoIma.setLayout(panelFondoImaLayout);
        panelFondoImaLayout.setHorizontalGroup(
            panelFondoImaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        panelFondoImaLayout.setVerticalGroup(
            panelFondoImaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelFondoIma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 470, 570));

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 51, 255));
        labelTitulo.setText("REGISTRARSE");
        panelPrincipal.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 260, 50));

        labelCorreo.setBackground(new java.awt.Color(0, 0, 0));
        labelCorreo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(255, 51, 255));
        labelCorreo.setText("Correo: ");
        panelPrincipal.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 150, 50));

        labelNombre.setBackground(new java.awt.Color(0, 0, 0));
        labelNombre.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 51, 255));
        labelNombre.setText("Nombre");
        panelPrincipal.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 50));

        labelConfirPass.setBackground(new java.awt.Color(0, 0, 0));
        labelConfirPass.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelConfirPass.setForeground(new java.awt.Color(255, 51, 255));
        labelConfirPass.setText("<html>Confirmar Password<html>");
        panelPrincipal.add(labelConfirPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 130, 50));

        labelPass.setBackground(new java.awt.Color(0, 0, 0));
        labelPass.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelPass.setForeground(new java.awt.Color(255, 51, 255));
        labelPass.setText("Password:");
        panelPrincipal.add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 50));

        txtCorreo.setBackground(new java.awt.Color(255, 51, 255));
        txtCorreo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        panelPrincipal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 230, 40));

        txtnombre.setBackground(new java.awt.Color(255, 51, 255));
        txtnombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 230, 40));

        txtUsuario.setBackground(new java.awt.Color(255, 51, 255));
        txtUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        panelPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 230, 40));

        txtConfirmarPass.setBackground(new java.awt.Color(255, 51, 255));
        txtConfirmarPass.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtConfirmarPass.setForeground(new java.awt.Color(0, 0, 0));
        panelPrincipal.add(txtConfirmarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 230, 40));

        txtPassword.setBackground(new java.awt.Color(255, 51, 255));
        txtPassword.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        panelPrincipal.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 230, 40));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        LabelRegisclick.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LabelRegisclick.setForeground(new java.awt.Color(0, 0, 0));
        LabelRegisclick.setText("       Registrarse");
        LabelRegisclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelRegisclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelRegisclickMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelRegisclick, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelRegisclick, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 220, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelRegresar.setText("jLabel1");
        labelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void labelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegresarMouseClicked
        // TODO add your handling code here:
        Prototipo regresar = new Prototipo();
        regresar.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_labelRegresarMouseClicked

    private void LabelRegisclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelRegisclickMouseClicked
        // TODO add your handling code here:

        sqlUsuarios modsql = new sqlUsuarios();
        usuarios mod = new usuarios();

        String pass = new String(txtPassword.getPassword());
        String confirmacion = new String(txtConfirmarPass.getPassword());

        if (txtUsuario.getText().equals("") || pass.equals("")
                || txtnombre.getText().equals("") || txtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe llenar todas las casillas", "Problema de autenticacion", JOptionPane.ERROR_MESSAGE);

        } else {

            if (pass.equals(confirmacion)) {

                if (modsql.UsuarioExistente(txtUsuario.getText()) == 0) {

                    String nuevoPass = hash.sha1(pass);

                    mod.setUsuario(txtUsuario.getText());
                    mod.setPassword(nuevoPass);
                    mod.setNombre(txtnombre.getText());
                    mod.setCorreo(txtCorreo.getText());
                    mod.setId_tipo(1);

                    if (modsql.registrar(mod)) {
                        JOptionPane.showMessageDialog(null, "Registro guardado");
                        LIMPIAR();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");

                }
            } else {

                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        }

    }//GEN-LAST:event_LabelRegisclickMouseClicked

    public void LIMPIAR() {

        txtnombre.setText("");
        txtUsuario.setText("");
        txtCorreo.setText("");
        txtPassword.setText("");
        txtConfirmarPass.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRegisclick;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelConfirPass;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelRegresar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelFondoIma;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField txtConfirmarPass;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
